planetarium/libplanet-seed

- Libplanet.Seed.Executable/Options.cs
> Make ICE server option optional

- Libplanet.Seed.Executable/Libplanet.Seed.Executable.csproj
- Libplanet.Seed.Executable/Program.cs
- Libplanet.Seed/Controllers/SeedController.cs
- Libplanet.Seed/Interfaces/IContext.cs
- Libplanet.Seed/Libplanet.Seed.csproj
- Libplanet.Seed/Queries/Query.cs
- Libplanet.Seed/SeedStartup.cs
> Bump libplanet

- Libplanet.Seed.Executable/Libplanet.Seed.Executable.csproj
- Libplanet.Seed/Libplanet.Seed.csproj
> Bump libplanet to 0.11.0-dev.20210129054518

- Libplanet.Seed.Executable/Libplanet.Seed.Executable.csproj
- Libplanet.Seed/Libplanet.Seed.csproj
> Bump libplanet to 0.11.0-dev.20210204113939

- Libplanet.Seed.Executable/Libplanet.Seed.Executable.csproj
- Libplanet.Seed/Libplanet.Seed.csproj
> Bump libplanet to 0.11.0-dev.20210205090355

- Libplanet.Seed.Executable/Options.cs
- Libplanet.Seed.Executable/Program.cs
This closes #6 by checking routing table periodically.
> Try add peers in static peer list

- Libplanet.Seed.Executable/Options.cs
- Libplanet.Seed.Executable/Program.cs
- README.md
Can configure minimum log level by `--log-level` or `-l` switch.
> Configurable log level

- .github/workflows/build.yml
> Add github action for build check

- Libplanet.Seed.Executable/Options.cs
- Libplanet.Seed.Executable/Program.cs
- Libplanet.Seed/SeedStartup.cs
Set default option of host and port to null, to use NAT traversal in `NetMQTransport`.
> Make TURN work

- Libplanet.Seed.Executable/Program.cs
Fixed a bug where seed was trying to connect to static peers.
> Remove bootstrap

- .github/workflows/docker_build_and_push.yml
> Add build and push docker image workflow

- Libplanet.Seed.Executable/Libplanet.Seed.Executable.csproj
- Libplanet.Seed/Libplanet.Seed.csproj
See also: https://github.com/planetarium/libplanet/releases/tag/0.20.0
> Upgrade Libplanet to 0.20.0

- Libplanet.Seed.Executable/Libplanet.Seed.Executable.csproj
- Libplanet.Seed/Libplanet.Seed.csproj
> bump libplanet to 0.22.1

- Libplanet.Seed.Executable/Libplanet.Seed.Executable.csproj
- Libplanet.Seed/Libplanet.Seed.csproj
> bump libplanet to 0.25.1

- Libplanet.Seed.Executable/Libplanet.Seed.Executable.csproj
- Libplanet.Seed/Libplanet.Seed.csproj
> Bump Libplanet to 0.26.0

- Libplanet.Seed.Executable/Libplanet.Seed.Executable.csproj
- Libplanet.Seed.Executable/Net/Seed.cs
- Libplanet.Seed/Libplanet.Seed.csproj
> Bump libplanet to 0.29.0

- Libplanet.Seed.Executable/Libplanet.Seed.Executable.csproj
- Libplanet.Seed.Executable/Options.cs
- Libplanet.Seed/Libplanet.Seed.csproj
> bump libplanet to 37.0

- Libplanet.Seed.Executable/Libplanet.Seed.Executable.csproj
- Libplanet.Seed.Executable/Net/Seed.cs
- Libplanet.Seed.Executable/Options.cs
- Libplanet.Seed.Executable/Program.cs
- Libplanet.Seed/Libplanet.Seed.csproj
> bump libplanet to 0.39

- Libplanet.Seed.Executable/Options.cs
- Libplanet.Seed.Executable/Program.cs
Make transport for gossip protocol.
> Introduce: Gossip transport

- Libplanet.Seed.Executable/Net/Seed.cs
When updating the table, remove the refresh candidate peers if they did not respond.
> feat: remove stale peers from table

- .github/workflows/build.yml
- Dockerfile
- Libplanet.Seed.Executable/Libplanet.Seed.Executable.csproj
- Libplanet.Seed.Executable/Net/Seed.cs
- Libplanet.Seed/Libplanet.Seed.csproj
Could you please take a look? 🙏 @greymistcube @limebell @OnedgeLee
> bump libplanet to 0.43.1 & Upgrade to net 6.0

- Libplanet.Seed.Executable/Libplanet.Seed.Executable.csproj
- Libplanet.Seed/Libplanet.Seed.csproj
> bump libplanet to 0.43.2

- Libplanet.Seed.Executable/Libplanet.Seed.Executable.csproj
- Libplanet.Seed/Libplanet.Seed.csproj
> Bump libplanet to 0.44.1

- .github/workflows/docker_build_and_push.yml
> Use organization-level environment variable

- .github/workflows/docker_build_and_push.yml
> fix docker build error

- Libplanet.Seed.Executable/Program.cs
- Libplanet.Seed/Interfaces/IContext.cs
- Libplanet.Seed/Queries/Query.cs
> Support query for the gossip peers
